 # Generated by Django 2.0.7 on 2018-07-19 17:53

from django.db import migrations
from django.apps import apps
import json

def create_minerals(apps, schema_editor):
	Mineral = apps.get_model('minerals', 'Mineral')
	with open('minerals/migrations/minerals.json', 'r', encoding='utf-8') as file:
		data = json.load(file)
	for mineral in data:
		Mineral.objects.create(
			name = mineral.get('name', ''),
            img_filename = mineral.get('image_filename', ''),
            img_caption = mineral.get('image_caption', ''),
            category = mineral.get('category', ''),
            formula = mineral.get('formula', ''),
            strunz_class = mineral.get('strunz_classification', ''),
            color = mineral.get('color', ''),
            crystal_sys = mineral.get('crystal_system', ''),
            unit_cell = mineral.get('unit_cell', ''),
            crystal_sym = mineral.get('crystal_symmetry', ''),
            cleavage =  mineral.get('cleavage', ''),
            mohs = mineral.get('mohs_scale_hardness', ''),
            luster = mineral.get('luster', ''),
            streak = mineral.get('streak', ''),
            diaphaneity = mineral.get('diaphaneity', ''),
            optical_prop = mineral.get('optical_properties', ''),
            refractive_inx = mineral.get('refractive_index', ''),
            crystal_habit = mineral.get('crystal_habit', ''),
            spec_gravity =  mineral.get('specific_gravity', '')
		)

class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
		migrations.RunPython(create_minerals)
    ]
